theme: jekyll-theme-cayman
github:
  zip_url:https://github.com/wenchieh/eaglemine/archive/5f4f59295ce1876f1e6c36eccfdb90356cc2e759.zip
title: Beyond outliers and on to micro-clusters: Vision-guided Anomaly Detection