# General Jekyll Config
name: Beyond outliers and on to micro-clusters: Vision-guided Anomaly Detection
description: The introduction of the EagleMine algorithm for Heatmap Mining and Anomaly Detection
url: wencheih.github.io/eaglemine

exclude: [LICENCE, README.md, .gitignore]

# Buld settings
permalink: pretty
theme: jekyll-theme-cayman
markdown: redcarpet
show_downloads:true
redcarpet:
  extensions: ["fenced_code_blocks", "autolink", "tables", "with_toc_data"]
